# cargo fmt config

# 最大行长
max_width = 150
# 链式调用的最大长度
chain_width = 100
# 数组的最大长度
array_width = 100
# 函数参数的最大长度
attr_fn_like_width = 100
# 函数调用参数的最大长度
fn_call_width = 80
# 简单函数格式化为单行
fn_single_line = true

# 自动对齐最大长度
enum_discrim_align_threshold = 5
# 字段初始化使用简写
use_field_init_shorthand = true
# 是否使用彩色输出
color = "Always"

edition = "2021"
