language = "简体中文"
language_set_to = "语言已经设置为：简体中文"
language_available = "可用语言列表: {}"

[main]
env.version.python = "Python 版本: {}"
env.version.DR = "Difficult_Rocket 版本: {}"
env.version.DR_rs = "Difficult_Rocket_rs 版本: {}"
env.version.pyglet = "pyglet 版本: {}"
env.version.pyglet_rs = "pyglet_rs 版本: {}"
version.now_on = "困难火箭的运行 Python 环境为"
version.need3p = "困难火箭需要 Python3.0+ 的环境"
version.best38p = "困难火箭是在 Python {write_py_v} 的环境下编写的，目前正在运行在Python {py_v}的环境下，可能产生BUG"
lang.language = "简 体 中 文 (zh-cn)"
logger.language = "日志记录语言为："
logger.created = "日志处理器创建完成"
logger.mkdir = "logs/ 文件夹不存在，已经新建文件夹"
logger.main_done = "主日志处理器创建完成"
logger.logfile_name = "日志文件文件名："
logger.logfile_level = "日志文件记录级别："
logger.logfile_fmt = "日志文件记录格式："
logger.logfile_datefmt = "日志文件日期格式："
game_start.at = "游戏主线程开始于："
mod.find.start = "正在校验 Mod: {}"
mod.find.faild.no_spec = "importlib 无法找到 spec"
mod.find.faild.no_mod_folder = "没有找到 Mod 文件夹"
mod.find.done = "所有 Mod 校验完成"
mod.load.start = "正在加载 Mod: {}"
mod.load.info = "mod id: {} 版本号: {}"
mod.load.faild.info = "Mod 加载失败: {} 错误信息: {}"
mod.load.faild.no_mod_class = "没有找到 Mod 类"
mod.load.done = "所有 Mod 加载完成"
mod.event.error = "Mod 事件 {} 发生错误 {} Mod: {}"

[client]
setup.start = "客户端加载开始"
setup.use_time = "客户端载入花费: {} 秒"
setup.use_time_ns = "客户端载入花费: {} 纳秒"
config.save.start = "正在保存配置文件"
config.save.done = "配置文件保存完成"

[window]
setup.start = "游戏窗口加载开始"
setup.use_time = "游戏窗口加载消耗时间: {} 秒"
setup.use_time_ns = "游戏窗口载入消耗时间: {} 纳秒"
os.pid_is = "游戏窗口 PID: {} PPID: {}"
button.been_press = "按钮被按下，目前状态为："
mouse.press = "鼠标在 {} 被按下，按键为：{}"
mouse.release = "鼠标在 {} 释放，按键为：{}"
mouse.RIGHT = "右键"
mouse.LEFT = "左键"
mouse.MIDDLE = "中键"
key.press = "按键 {} | {} 被按下"
key.release = "按键 {} | {} 被释放"
text.input = "输入字符 \"{}\""
text.new_line = "换行"
text.motion = "光标移动 {}"
text.motion_select = "光标选择 {}"
command.text = "输入命令: {}"
message.text = "输入信息: {}"
libs.local = "正在使用本地 pyglet 库 版本为: {}"
libs.outer = "正在使用全局 pyglet 库 版本为: {}\n(可能会造成bug，因为本地库版本为2.0dev9)"
fonts.found = "在字体列表中找到以下字体库: {}"
fonts.load = "正在加载字体: {}"
game.stop_get = "从{}传入关闭指令,关闭游戏中"
game.stop = "游戏正在关闭,保存数据中···"
game.end = "游戏已经关闭"

[server]
setup.start = "服务端开始加载"
setup.use_time = "服务端加载消耗时间: {} 秒"
os.pid_is = "服务端 PID: {} PPID: {}"

[game]
input = "控制台"
command = "游戏内命令行"
window = "窗口"
require_DR_rs = "需要 DR_rs 模块"

[client.sr1_render]
setup.start = "SR1 渲染器开始载入"
setup.use_time = "SR1 渲染器载入消耗时间: {} 秒"
xml.loading = "正在加载XML文件: {}"
xml.load_done = "XML 文件加载完成"
xml.load_time = "XML 文件加载消耗时间: {} 秒"
ship.load = "正在加载飞船: {}"
ship.load_time = "飞船加载消耗时间: {} 秒"
#ship.info = "飞船信息:\n- 部件数量: {}\n- 部件重量: {}\n- 文件大小: {}"
ship.info = "飞船信息:\n- 部件数量: {}\n- 部件重量: {}"
ship.render.done = "飞船渲染完成"
